services:
  client:
    build:
      context: ./client
    ports:
      - "4173:80"
    env_file:
      - .env.production
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024M'

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    env_file:
      - .env.production
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  db_data: